PROGRAM fortranMath
	IMPLICIT NONE
	!comment Here
	CHARACTER(LEN=11) :: HELLO
	CHARACTER(LEN=11) :: HELLO = 'HELLO WORLD'
	REAL :: MATH, MATH2
	REAL :: MATH=25
	REAL :: MATH2=SQRT(MATH)
	PRINT HELLO
	PRINT MATH2
	!This is FORTRAN 77 code

END PROGRAM fortranMath

